/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donation;

/**
 *
 * @author Schrodinger's Cat
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
import java.sql.*; 
import java.sql.PreparedStatement;

public class Event extends javax.swing.JFrame {

    /**
     * Creates new form Event
     */
    Connection con1=null;
    Statement stat1=null;
    ResultSet result1=null;
    ResultSetMetaData meta1=null;
    String g;
    public Event() {
        initComponents();
    }
    public Event(String lx)
    {
        initComponents();
        this.g=lx;
        connection();
    }
    
        public void connection(){
        try{
           con1= DriverManager.getConnection("jdbc:derby://localhost:1527/Project370", "RIMSHANAF", "RIMSHANAF");
           stat1=con1.createStatement();
//           String g=menu.combo.getSelectedItem().toString();
           String x="SELECT * FROM RIMSHANAF."+g;
//           System.out.println(g);
           result1=stat1.executeQuery(x);
           etable.setModel(DbUtils.resultSetToTableModel(result1));
           if(g.compareTo("Product")==0)
           {
                col1.setText("Product_ID");
                col2.setText("Type");
                col3.setText("Size");
                col4.setText("Event_ID");
                col5.setText("Donor_ID");
           }
           else{
                col1.setText("Event_ID");
                col2.setText("Event_name");
                col3.setText("Date");
                col4.setText("Place");
                col5.setText("Leader_ID");
           }
        }
        catch(Exception e){
            new ConnectionErr().setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        etable = new javax.swing.JTable();
        col1 = new javax.swing.JTextField();
        col2 = new javax.swing.JTextField();
        col3 = new javax.swing.JTextField();
        col4 = new javax.swing.JTextField();
        col5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(etable);

        col1.setText("Column 1");

        col2.setText("Column 2");

        col3.setText("Column 3");
        col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col3ActionPerformed(evt);
            }
        });

        col4.setText("Column 4");

        col5.setText("Column 5");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(search))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete)
                            .addComponent(update)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(col1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(col2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(col4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(col3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(col5)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(col1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(col2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(col3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(col4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(col5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void col3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_col3ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try{
            String x="insert into RIMSHANAF."+g+" values (?,?,?,?,?)";
            PreparedStatement ad=con1.prepareStatement(x);   
            ad.setString(1,col1.getText());
            ad.setString(2,col2.getText());
            ad.setString(3,col3.getText());
            ad.setString(4,col4.getText());
            ad.setString(5,col5.getText());
            int row=ad.executeUpdate();
            }
        catch(Exception e){
            new Invalid().setVisible(true);
        }
        connection();
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            String x=null;
            if(g.compareTo("Product")==0)
            {
                x="Delete from RIMSHANAF."+g+" where "+g+"_id="+"'"+col1.getText()+"'";
            }
            else{
                x="Delete from RIMSHANAF."+g+" where event_id="+"'"+col1.getText()+"'";
            }
//            System.out.println(x);
            Statement del=con1.createStatement();
            del.executeUpdate(x);
//            col1.setText("Column 1");
//            col2.setText("Column 2");
//            col3.setText("Column 3");
//            col4.setText("Column 4");
//            col5.setText("Column 5");
        }catch(Exception e)
        {
            new Invalid().setVisible(true);
        }
        connection();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            String x=null;
            if(g.compareTo("Events")==0){
                x="update RIMSHANAF."+g+" set event_name='"+col2.getText()+"', Date='"+col3.getText()+"', place='"+col4.getText()+"' ,leader_id='"+col5.getText()+"' where Event_id='"+col1.getText()+"'";
            }
            else{
                x="update RIMSHANAF."+g+" set type='"+col2.getText()+"', size='"+col3.getText()+"', event_id='"+col4.getText()+"' ,donor_id='"+col5.getText()+"' where "+g+"_id='"+col1.getText()+"'";
            }
            //System.out.println(x);
            Statement up=con1.createStatement();
            up.executeUpdate(x);
        }catch(Exception e){
            new Invalid().setVisible(true);
        }
        connection();
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        connection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
            try{
            String x=null;
            if(g.compareTo("Events")==0)
            {
                x="SELECT * FROM RIMSHANAF."+g+" where Event_id='"+col1.getText()+"'";
            }
            else{
                x="SELECT * FROM RIMSHANAF."+g+" where "+g+"_id='"+col1.getText()+"'";
            }
            
//            System.out.println(x);
//            Statement up=con1.createStatement();
//            up.executeUpdate(x);
            Connection con2= DriverManager.getConnection("jdbc:derby://localhost:1527/Project370", "RIMSHANAF", "RIMSHANAF");
            Statement stat2=con2.createStatement();
            ResultSet result2=stat2.executeQuery(x);
            etable.setModel(DbUtils.resultSetToTableModel(result2));
        }catch(Exception e){
            new ConnectionErr().setVisible(true);
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField col1;
    private javax.swing.JTextField col2;
    private javax.swing.JTextField col3;
    private javax.swing.JTextField col4;
    private javax.swing.JTextField col5;
    private javax.swing.JButton delete;
    private javax.swing.JTable etable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
