/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donation;

/**
 *
 * @author Schrodinger's Cat
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
import java.sql.*; 
import java.sql.PreparedStatement;

public class Join extends javax.swing.JFrame {

    /**
     * Creates new form Join
     */
    Connection con1=null;
    Statement stat1=null;
    ResultSet result1=null;
    ResultSetMetaData meta1=null;
    String g;
    public Join() {
        initComponents();
    }
    public Join(String lx){
        initComponents();
        g=lx;
        connection();
    }
    public void connection(){
        try{
           con1= DriverManager.getConnection("jdbc:derby://localhost:1527/Project370", "RIMSHANAF", "RIMSHANAF");
           stat1=con1.createStatement();
//           String g=menu.combo.getSelectedItem().toString();
           String x=null;
           if(g.compareTo("Donor & Product")==0){
               x="Select Donor.Donor_id, Donor.Donor_name, Product.Product_id, Product.type, Product.size from RIMSHANAF.Donor inner join RIMSHANAF.Product on Donor.Donor_id=Product.Donor_id";
               tableg.setText("Donor_ID");
               tablegg.setText("Product_ID");
           }
           else if(g.compareTo("Product and Events")==0)
           {
               x="Select Product.Product_id, Product.type, Product.size, Events.Event_id, Events.Event_name, Events.place from RIMSHANAF.Product inner join RIMSHANAF.Events on Product.Event_id=Events.Event_id";
               tableg.setText("Product_ID");
               tablegg.setText("Event_ID");
           }
           else{
               x="Select Events.Event_id, Events.Event_name, Events.place, Events.Leader_id, Volunteer.volunteer_name as Leader_name from RIMSHANAF.Events inner join RIMSHANAF.Volunteer on Events.Leader_id=Volunteer.volunteer_id";
               tableg.setText("Event_ID");
               tablegg.setText("Volunteer_ID");
           }
//           System.out.println(g);
           result1=stat1.executeQuery(x);
           table.setModel(DbUtils.resultSetToTableModel(result1));
        }
        catch(Exception e){
            new ConnectionErr().setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tableg = new javax.swing.JTextField();
        tablegg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        tableg.setText("Table1 ID");

        tablegg.setText("Table2 ID");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("REFRESH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tableg, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(tablegg))
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(tableg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(tablegg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(49, 49, 49)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        String x=null;
            if(g.compareTo("Donor & Product")==0){
                x="Select Donor.Donor_id, Donor.Donor_name, Product.Product_id, Product.type, Product.size from RIMSHANAF.Donor inner join RIMSHANAF.Product on Donor.Donor_id=Product.Donor_id where Donor.Donor_id='"+tableg.getText()+"'";
            }
            else if(g.compareTo("Product and Events")==0)
            {
                x="Select Product.Product_id, Product.type, Product.size, Events.Event_id, Events.Event_name, Events.place from RIMSHANAF.Product inner join RIMSHANAF.Events on Product.Event_id=Events.Event_id where Product.Product_id='"+tableg.getText()+"'";
            }
            else{
                x="Select Events.Event_id, Events.Event_name, Events.place, Events.Leader_id, Volunteer.volunteer_name as Leader_name from RIMSHANAF.Events inner join RIMSHANAF.Volunteer on Events.Leader_id=Volunteer.volunteer_id where Events.Event_id='"+tableg.getText()+"'";
            }
            Connection con2= DriverManager.getConnection("jdbc:derby://localhost:1527/Project370", "RIMSHANAF", "RIMSHANAF");
            Statement stat2=con2.createStatement();
            ResultSet result2=stat2.executeQuery(x);
            table.setModel(DbUtils.resultSetToTableModel(result2));
        }catch(Exception e){
            new ConnectionErr().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        String x=null;
            if(g.compareTo("Donor & Product")==0){
                x="Select Donor.Donor_id, Donor.Donor_name, Product.Product_id, Product.type, Product.size from RIMSHANAF.Donor inner join RIMSHANAF.Product on Donor.Donor_id=Product.Donor_id where Product.Product_id='"+tablegg.getText()+"'";
            }
            else if(g.compareTo("Product and Events")==0)
            {
                x="Select Product.Product_id, Product.type, Product.size, Events.Event_id, Events.Event_name, Events.place from RIMSHANAF.Product inner join RIMSHANAF.Events on Product.Event_id=Events.Event_id where Events.Event_id='"+tablegg.getText()+"'";
            }
            else{
                x="Select Events.Event_id, Events.Event_name, Events.place, Events.Leader_id, Volunteer.volunteer_name as Leader_name from RIMSHANAF.Events inner join RIMSHANAF.Volunteer on Events.Leader_id=Volunteer.volunteer_id where Volunteer.Volunteer_id='"+tablegg.getText()+"'";
            }
            Connection con2= DriverManager.getConnection("jdbc:derby://localhost:1527/Project370", "RIMSHANAF", "RIMSHANAF");
            Statement stat2=con2.createStatement();
            ResultSet result2=stat2.executeQuery(x);
            table.setModel(DbUtils.resultSetToTableModel(result2));
        }catch(Exception e){
            new ConnectionErr().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        connection();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Join().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tableg;
    private javax.swing.JTextField tablegg;
    // End of variables declaration//GEN-END:variables
}
